//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.08 at 06:58:36 PM CET 
//
package edu.uz.jira.event.planner.database.importer.xml.model;

import edu.uz.jira.event.planner.project.plan.rest.ActiveObjectWrapper;
import net.java.ao.Entity;
import net.java.ao.RawEntity;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * XML representation of many Event Plans.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "eventPlan"
})
@XmlRootElement(name = "event-plans")
public class AllEventPlans implements ActiveObjectWrapper {
    @XmlElement(name = "event-plan")
    private List<EventPlan> eventPlan;

    public List<EventPlan> getEventPlan() {
        if (eventPlan == null) {
            eventPlan = new ArrayList<EventPlan>();
        }
        return this.eventPlan;
    }

    public void setEventPlan(List<EventPlan> eventPlan) {
        this.eventPlan = eventPlan;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        AllEventPlans that = (AllEventPlans) o;

        return !(getEventPlan() != null ? !getEventPlan().equals(that.getEventPlan()) : that.getEventPlan() != null);
    }

    @Override
    public int hashCode() {
        return getEventPlan() != null ? getEventPlan().hashCode() : 0;
    }

    @Override
    public Class<? extends RawEntity> getWrappedType() {
        throw new UnsupportedOperationException();
    }

    @Override
    public ActiveObjectWrapper fill(Entity entity) {
        throw new UnsupportedOperationException();
    }

    @Override
    public boolean isFullfilled() {
        return !eventPlan.isEmpty();
    }

    @Override
    public ActiveObjectWrapper getEmptyCopy() {
        return new AllEventPlans();
    }
}
